sudo: required
services:
  - docker

language: node_js
node_js:
  - 8.11
  - 10.4

dist: trusty
addons:
  chrome: stable
  firefox: latest
env:
  - MOZ_HEADLESS=1
cache:
  directories:
    - node_modules
    - example/node/node_modules

before_install:
- echo "before install"

install:
- cd ${TRAVIS_BUILD_DIR} && npm i
- cd ${TRAVIS_BUILD_DIR}/example/node && npm i

script:
- cd ${TRAVIS_BUILD_DIR} && npm t
- cd ${TRAVIS_BUILD_DIR}/example/node && npm run build

after_success:
- cat ${TRAVIS_BUILD_DIR}/logs/*.log
- sudo rm -f ${TRAVIS_BUILD_DIR}/logs/*.log
- if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "commit on master"; fi
