sudo: required
services:
  - docker

language: node_js
node_js:
  - 8.11
  - 10.4

dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules

before_install:
- echo "before install"

install:
- npm i

script:
- npm t

after_success:
- cat $TRAVIS_BUILD_DIR/logs/*.log
- sudo rm -f $TRAVIS_BUILD_DIR/logs/*.log
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "commit on master"; fi
